theme: jekyll-theme-architect

title: [Free Libre Open Source Lebanon]
description: [The Open Source lebanese movement @ Lebanon lb]

# sidebar links url
links:
  #download: https://github.com/javaee/
  source: http://oslm.cofares.net 
  #mailinglist:
  javadocs: http://java.cofares.net
  docs:  http://ljug.cofares.net
  #faq:
  #mailinglist:
  hide_issuetracker: false

sidebar:
  nav: "docs"

navbar-links:
  About Me: "aboutme"
  Resources:
    - Open Source Lebense Mobement: "http://oslm.cofares.net/"
    - Learn markdown: "http://www.markdowntutorial.com/"
    - GitHub Pages: "https://pages.github.com/"
  Author's home: "http://www.cofares.net"


author: Pascal Fares

author_email: pascal.fares@cofares.net

google_analytics: UA-24954673-1
  
